// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogError is an autogenerated mock type for the LogError type
type LogError struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err
func (_m *LogError) Execute(err error) {
	_m.Called(err)
}

type mockConstructorTestingTNewLogError interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogError creates a new instance of LogError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogError(t mockConstructorTestingTNewLogError) *LogError {
	mock := &LogError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
